<a href="https://colab.research.google.com/github/sap0408/2048/blob/master/Copy_of_Copy_of_MejorandoRendimiento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install tensorflow

In [0]:
import tensorflow as tf
print (tf.__version__)

2.2.0


In [0]:
import warnings
warnings.filterwarnings("ignore")
import keras
keras.__version__

Using TensorFlow backend.


'2.3.1'

In [0]:
#One hot con palabras
import numpy as np

# En este ejemplo de juguete, una "muestra" es solo una oración, pero
# podría ser un documento completo.
samples = ['El gato rasguño mi alfonbra.', 'El perro se comio mi tarea.']

# Creamos índice para todos los tokens en los datos.
token_index = {}
for sample in samples:
    # Simplemente tokenizamos las muestras mediante el método `split`. En la vida real, 
    # también eliminaríamos la puntuación y los caracteres especiales de las muestras.
    for word in sample.split():
        if word not in token_index:
            # Asignar un índice único a cada palabra única
            token_index[word] = len(token_index) + 1
            # Tenga en cuenta que no atribuimos el índice 0 a nada.
print(token_index)

# A continuación, vectorizamos nuestras muestras.
# Solo consideraremos las primeras palabras `max_length` en cada muestra.
max_length = 5

# Aquí es donde almacenamos nuestros resultados:
results = np.zeros((len(samples), max_length, max(token_index.values()) + 1))
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = token_index.get(word)
        results[i, j, index] = 1.
print(results) 

{'El': 1, 'gato': 2, 'rasguño': 3, 'mi': 4, 'alfonbra.': 5, 'perro': 6, 'se': 7, 'comio': 8, 'tarea.': 9}
[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]]


In [0]:
#One hot con caracteres
import string

samples = ['El gato rasguño mi alfonbra.', 'El perro se comio mi tarea.']

characters = string.printable  # Todos los caracteres ASCII imprimibles.
token_index = dict(zip(characters, range(1, len(characters) + 1)))

print(token_index)

max_length = 3 #50
results = np.zeros((len(samples), max_length, max(token_index.values()) + 1))
for i, sample in enumerate(samples):
    for j, character in enumerate(sample[:max_length]):
        index = token_index.get(character)
        results[i, j, index] = 1.
print(results)

{'0': 1, '1': 2, '2': 3, '3': 4, '4': 5, '5': 6, '6': 7, '7': 8, '8': 9, '9': 10, 'a': 11, 'b': 12, 'c': 13, 'd': 14, 'e': 15, 'f': 16, 'g': 17, 'h': 18, 'i': 19, 'j': 20, 'k': 21, 'l': 22, 'm': 23, 'n': 24, 'o': 25, 'p': 26, 'q': 27, 'r': 28, 's': 29, 't': 30, 'u': 31, 'v': 32, 'w': 33, 'x': 34, 'y': 35, 'z': 36, 'A': 37, 'B': 38, 'C': 39, 'D': 40, 'E': 41, 'F': 42, 'G': 43, 'H': 44, 'I': 45, 'J': 46, 'K': 47, 'L': 48, 'M': 49, 'N': 50, 'O': 51, 'P': 52, 'Q': 53, 'R': 54, 'S': 55, 'T': 56, 'U': 57, 'V': 58, 'W': 59, 'X': 60, 'Y': 61, 'Z': 62, '!': 63, '"': 64, '#': 65, '$': 66, '%': 67, '&': 68, "'": 69, '(': 70, ')': 71, '*': 72, '+': 73, ',': 74, '-': 75, '.': 76, '/': 77, ':': 78, ';': 79, '<': 80, '=': 81, '>': 82, '?': 83, '@': 84, '[': 85, '\\': 86, ']': 87, '^': 88, '_': 89, '`': 90, '{': 91, '|': 92, '}': 93, '~': 94, ' ': 95, '\t': 96, '\n': 97, '\r': 98, '\x0b': 99, '\x0c': 100}
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0

In [0]:
#One hot con palabras, PERO usando Keras
from keras.preprocessing.text import Tokenizer

samples = ['El gato rasguño mi alfonbra.', 'El perro se comio mi tarea.']

# Creamos un tokenizador, configurado para tomar solo
# en cuenta las 20 palabras más comunes
tokenizer = Tokenizer(num_words=20)
# This builds the word index
tokenizer.fit_on_texts(samples)


# Esto convierte las cadenas en listas de índices enteros.
sequences = tokenizer.texts_to_sequences(samples)
print(samples)
print(sequences)

# También puede obtener directamente las representaciones binarias.
one_hot_results = tokenizer.texts_to_matrix(samples, mode='binary')

# Así es como puede recuperar el índice de palabras que se calculó
word_index = tokenizer.word_index
print('Se encontrarom %s tokens unicos.' % len(word_index))
print(one_hot_results)

['El gato rasguño mi alfonbra.', 'El perro se comio mi tarea.']
[[1, 3, 4, 2, 5], [1, 6, 7, 8, 2, 9]]
Se encontrarom 9 tokens unicos.
[[0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [0]:
#Codificación hash
#One hot hash con palabras
samples = ['El gato rasguño mi alfonbra.', 'El perro se comio mi tarea.']

# Almacenaremos nuestras palabras como vectores de tamaño 10.
# Tenga en cuenta que si tiene cerca de 10 palabras (o más)
# comenzará a ver muchas colisiones de hash, que
# disminuirá la precisión de este método de codificación.
dimensionality = 5
max_length = 10

results = np.zeros((len(samples), max_length, dimensionality))
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        # Hashear la palabra en un índice entero "aleatorio" que está entre 0 y 10
        index = abs(hash(word)) % dimensionality
        results[i, j, index] = 1.
results

array([[[0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [0]:
#Usar vectores de palabras (embeddings)
#Capa embedding de Keras
from keras.layers import Embedding
from keras.models import Sequential
from keras.layers import Flatten, Dense

model = Sequential()
model.add(Embedding(10, 3, input_length=5))
# 5 entradas de numeros menosres a 10 se trasnforman en 5 vectores de 3 conponenetes
# El modelo tomará como entrada una matriz entera de tamaño (lote, 5)
# y el entero más grande en cada entrada no debe ser mayor que 999 (tamaño de vocabulario).
# Ahora model.output_shape es (None, 5, 10), donde `None` es el lote.
model.compile('rmsprop', 'mse')
output_array = model.predict(np.array([[1, 8, 7, 5, 4]]))
print("Salida: "+ str(output_array))
print("\nTamano: "+ str(output_array.shape)+"\n")
model.summary()

Salida: [[[-4.5827854e-02  1.0089390e-03 -4.5176517e-02]
  [ 3.9318312e-02 -2.3258125e-02 -1.1512265e-03]
  [-2.0147717e-02 -1.5355658e-02 -4.2808153e-02]
  [ 5.3420663e-06  8.4328279e-03  4.1656028e-02]
  [ 4.0496740e-02 -1.7721556e-02  5.8554523e-03]]]

Tamano: (1, 5, 3)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 5, 3)              30        
Total params: 30
Trainable params: 30
Non-trainable params: 0
_________________________________________________________________


In [0]:
#EJEMPLO IMDB
from keras.datasets import imdb
from keras import preprocessing

# Número de palabras a considerar
max_features = 10000

# Cortar textos después de este número de palabras
maxlen = 40

# Cargue los datos como listas de enteros.
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)
print("Train x: "+str(x_train.shape))
print("Test x: "+str(x_test.shape))
print("Train y: "+str(y_train.shape))
print("Test y: "+str(y_test.shape))

17465344/17464789 [==============================] - 0s 0us/step
Train x: (25000,)
Test x: (25000,)
Train y: (25000,)
Test y: (25000,)


In [0]:
resena=5
print("\nOpinion 11: "+str(x_train[resena]))
print("\nSentimiento 11: "+str(y_train[resena]))


Opinion 11: [1, 778, 128, 74, 12, 630, 163, 15, 4, 1766, 7982, 1051, 2, 32, 85, 156, 45, 40, 148, 139, 121, 664, 665, 10, 10, 1361, 173, 4, 749, 2, 16, 3804, 8, 4, 226, 65, 12, 43, 127, 24, 2, 10, 10]

Sentimiento 11: 0


In [0]:
word_index = imdb.get_word_index()

# Lo revertimos, mapeando índices enteros a palabras.
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])

# Decodificamos la resena; tenga en cuenta que nuestros índices fueron compensados por 3
# porque 0, 1 y 2 son índices reservados para "relleno", "inicio de secuencia" y "desconocido".
decoded_review = ' '.join([reverse_word_index.get(i - 3, '?') for i in x_train[resena]])
decoded_review

1646592/1641221 [==============================] - 0s 0us/step


"? begins better than it ends funny that the russian submarine crew ? all other actors it's like those scenes where documentary shots br br spoiler part the message ? was contrary to the whole story it just does not ? br br"

In [0]:
# Esto convierte nuestras listas de enteros en un tensor de forma 2D `(samples, maxlen)`
x_train = preprocessing.sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = preprocessing.sequence.pad_sequences(x_test, maxlen=maxlen)
print("Train x: "+str(x_train.shape))
print("Test x: "+str(x_test.shape))
print("Train y: "+str(y_train.shape))
print("Test y: "+str(y_test.shape))
print("Opinion 11: "+str(x_train[resena][:]))
print("Sentimiento 11: "+str(y_train[1]))
decoded_review = ' '.join([reverse_word_index.get(i - 3, '?') for i in x_train[resena][:]])
decoded_review

Train x: (25000, 40)
Test x: (25000, 40)
Train y: (25000,)
Test y: (25000,)
Opinion 11: [  74   12  630  163   15    4 1766 7982 1051    2   32   85  156   45
   40  148  139  121  664  665   10   10 1361  173    4  749    2   16
 3804    8    4  226   65   12   43  127   24    2   10   10]
Sentimiento 11: 0


"than it ends funny that the russian submarine crew ? all other actors it's like those scenes where documentary shots br br spoiler part the message ? was contrary to the whole story it just does not ? br br"

In [0]:
model = Sequential()

# Especificamos la longitud máxima de entrada a nuestra capa de incrustación  para que
# luego podamos aplanar las entradas incrustadas
model.add(Embedding(10000, 8, input_length=maxlen))

# Después de la capa de incrustación, nuestras activaciones tienen forma `(samples, maxlen, 8)`.

# Aplanamos el tensor 3D de incrustaciones en un tensor 2D `(samples, maxlen * 8)`
model.add(Flatten())

# Agregamos el clasificador en la parte superior
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 40, 8)             80000     
_________________________________________________________________
flatten_1 (Flatten)          (None, 320)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 321       
Total params: 80,321
Trainable params: 80,321
Non-trainable params: 0
_________________________________________________________________


In [0]:
history = model.fit(x_train, y_train,
                    epochs=10,
                    batch_size=32,
                    validation_split=0.2)

Train on 20000 samples, validate on 5000 samples
Epoch 1/10
20000/20000 [==============================] - 2s 79us/step - loss: 0.6506 - acc: 0.6532 - val_loss: 0.5618 - val_acc: 0.7472
Epoch 2/10
20000/20000 [==============================] - 1s 67us/step - loss: 0.4731 - acc: 0.7945 - val_loss: 0.4574 - val_acc: 0.7818
Epoch 3/10
20000/20000 [==============================] - 1s 65us/step - loss: 0.3905 - acc: 0.8293 - val_loss: 0.4317 - val_acc: 0.7920
Epoch 4/10
20000/20000 [==============================] - 1s 65us/step - loss: 0.3518 - acc: 0.8470 - val_loss: 0.4272 - val_acc: 0.8008
Epoch 5/10
20000/20000 [==============================] - 1s 65us/step - loss: 0.3247 - acc: 0.8613 - val_loss: 0.4275 - val_acc: 0.8016
Epoch 6/10
20000/20000 [==============================] - 1s 65us/step - loss: 0.3027 - acc: 0.8717 - val_loss: 0.4305 - val_acc: 0.8004
Epoch 7/10
20000/20000 [==============================] - 1s 64us/step - loss: 0.2825 - acc: 0.8849 - val_loss: 0.4385 - val_acc:

In [0]:
from zipfile import ZipFile
file_name = "aclImdb.zip"
with ZipFile(file_name, 'r') as zip:
  zip.extractall()
  print('Done')

Done


In [7]:
from zipfile import ZipFile
file_name = "glove.6B.zip"
with ZipFile(file_name, 'r') as zip:
  zip.extractall()
  print('Done')

BadZipFile: ignored

In [0]:
import os

imdb_dir = os.getcwd()
train_dir = os.path.join(imdb_dir, 'aclImdb', 'train')
print(train_dir)

labels = []
texts = []

for label_type in ['neg', 'pos']:
    dir_name = os.path.join(train_dir, label_type)
    for fname in os.listdir(dir_name):
        if fname[-4:] == '.txt':
            f = open(os.path.join(dir_name, fname), encoding="utf8")
            texts.append(f.read())
            f.close()
            if label_type == 'neg':
                labels.append(0)
            else:
                labels.append(1)

/content/aclImdb/train


In [8]:
print("\nNumero de opiniones de entraenamiento: "+str(len(texts)))    
print("\nNumero de labels: "+str(len(texts)))  
print("\nEjemplo:\n "+str(texts[5]))


Numero de opiniones de entraenamiento: 25000

Numero de labels: 25000

Ejemplo:
 Watching this Movie? l thought to myself, what a lot of garbage. These girls must have rocks for brains for even agreeing to be part of it. Waste of time watching it, faint heavens l only hired it. The acting was below standard and story was unbearable. Anyone contemplating watching this film, please save your money. The film has no credit at all. l am a real film buff and this is worse than "Attack of the Green Tomatoes".<br /><br />l only hope that this piece of trash didn't cost too much to make. Money would have been better spent on the homeless people of the world. l only hope there isn't a sequel in the pipeline.


In [9]:
#tokenizar datos
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np

maxlen = 100  # Cortaremos las reseñas después de 100 palabras.
training_samples = 200  # Entrenaremos con 200 muestras.
validation_samples = 10000  # Validaremos en 10000 muestras.
max_words = 10000  # Solo consideraremos las 10.000 palabras principales en el conjunto de datos

tokenizer = Tokenizer(num_words=max_words)

tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

word_index = tokenizer.word_index
print('Se encontraron %s tokens unicos.' % len(word_index))

Using TensorFlow backend.


Se encontraron 88582 tokens unicos.


In [10]:
print(list(tokenizer.word_counts)[:50])

['hayden', 'christianson', 'and', 'jessica', 'alba', 'two', 'of', 'my', 'least', 'favourite', 'actors', 'this', 'century', 'team', 'up', 'in', 'what', 'is', 'quite', 'possibly', 'the', 'flattest', 'attempt', 'at', 'remake', 'already', 'dire', 'butterfly', 'effect', 'awake', 'so', 'dull', 'utterly', 'uninteresting', 'that', "you'd", 'be', 'better', 'off', 'asleep', 'terrance', 'howard', 'still', 'recovering', 'from', 'diabolical', 'august', 'rush', 'puts', 'a']


In [11]:
data = pad_sequences(sequences, maxlen=maxlen)

labels = np.asarray(labels)
print('Forma del tensor de datos:', data.shape)
print('Forma del tensor de etiquetas:', labels.shape)

# Divide los datos en un conjunto de entrenamiento y un conjunto de validación
# Pero primero, baraja los datos, ya que comenzamos con los datos como se 
# ordenan las muestras (todas negativas primero, luego todas positivas).
indices = np.arange(data.shape[0])
np.random.shuffle(indices)
data = data[indices]
labels = labels[indices]

x_train = data[:training_samples]
y_train = labels[:training_samples]
x_val = data[training_samples: training_samples + validation_samples]
y_val = labels[training_samples: training_samples + validation_samples]

Forma del tensor de datos: (25000, 100)
Forma del tensor de etiquetas: (25000,)
